import { useState } from 'react';
export default function EventBank({ templates, onSave, onUse, busy, canManage = true, touchHandle }) {
  const [draft, setDraft] = useState(null);
  return <aside className="event-bank" aria-label="בנק אירועים"><p>תבניות לשימוש חוזר. גררו ליום בלוח או בחרו ״הוספה״. עריכת תבנית לא משנה אירועים שכבר נוצרו.</p>
    <div className="event-bank-items">{templates.map(item => <article key={item.id} draggable={!busy} onDragStart={event => { event.dataTransfer.setData('application/x-zoko-calendar', JSON.stringify({ templateId:item.id })); event.dataTransfer.effectAllowed='copy'; }}><button className="calendar-touch-grip" type="button" aria-label={`גרירת ${item.title}`} {...touchHandle({templateId:item.id})}>⠿</button><strong>{item.title}</strong><div><button className="btn btn-secondary" disabled={busy} onClick={() => onUse(item)}>הוספה ללוח</button><button className="btn btn-secondary" disabled={busy || !canManage} onClick={() => setDraft({...item})}>עריכת תבנית</button></div></article>)}</div>
    <button className="btn btn-secondary" disabled={busy || !canManage} onClick={() => setDraft({id:crypto.randomUUID(),title:'',description:'',color:'#fed7aa'})}>תבנית חדשה</button>
    {draft && <form className="event-bank-editor" onSubmit={async event => { event.preventDefault(); if(!draft.title.trim())return; const updated={...draft,title:draft.title.trim()};const next=templates.some(item=>item.id===draft.id)?templates.map(item=>item.id===draft.id?updated:item):[...templates,updated];if(await onSave(next))setDraft(null); }}><label>שם האירוע<input required maxLength={180} value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label>תיאור<textarea maxLength={3000} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></label><div><button className="btn btn-primary" disabled={busy}>שמירת תבנית</button><button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>setDraft(null)}>ביטול</button></div></form>}
  </aside>;
}
