export const PERMISSION_GROUPS = Object.freeze([
  Object.freeze({ id: 'staff', label: 'אנשי צוות והזמנות', permissions: [
    ['staff.view', 'צפייה באנשי צוות'],
    ['staff.invite', 'שליחת הזמנות לאנשי צוות'],
    ['staff.edit', 'עריכת פרטי אנשי צוות'],
    ['staff.remove', 'הסרת איש צוות'],
    ['staff.assignRoles', 'הקצאת תפקידים לאנשי צוות'],
    ['staff.viewJoinRequests', 'צפייה בבקשות הצטרפות'],
    ['staff.reviewJoinRequests', 'טיפול בבקשות הצטרפות'],
    ['staff.resetPassword', 'שליחת קישור איפוס סיסמה'],
  ] }),
  Object.freeze({ id: 'tasks', label: 'משימות ושיתופים', permissions: [
    ['tasks.viewOwn', 'צפייה במשימות אישיות'],
    ['tasks.viewTeam', 'צפייה במשימות צוות'],
    ['tasks.viewAll', 'צפייה בכל משימות המוסד'],
    ['tasks.create', 'יצירת משימות'],
    ['tasks.assign', 'הקצאת משימות'],
    ['tasks.editAll', 'עריכת כל משימות המוסד'],
    ['tasks.deleteAll', 'מחיקת כל משימות המוסד'],
    ['tasks.managePermissions', 'ניהול הרשאות נקודתיות למשימות'],
    ['tasks.inviteCollaborators', 'הזמנת שותפים למשימה אישית'],
    ['tasks.assignMandatory', 'הקצאת משימה מחייבת'],
    ['tasks.manageAssignments', 'ביטול ושינוי הקצאות משימה'],
    ['tasks.useAssistant', 'שימוש בסוכן יצירת משימות'],
  ] }),
  Object.freeze({ id: 'communications', label: 'מיילים ומעקבים', permissions: [
    ['communications.create', 'יצירת טיוטת מייל ומשימת מעקב'],
    ['communications.viewOwn', 'צפייה במיילים ובמעקבים אישיים'],
    ['communications.viewTeam', 'צפייה במעקבים משותפים לצוות'],
    ['communications.viewAll', 'צפייה במעקבים המוסדיים המורשים'],
    ['communications.reassign', 'העברת אחריות למעקב'],
    ['communications.close', 'סגירת טיפול'],
    ['communications.useAgent', 'שימוש בסוכן ניסוח מייל'],
    ['communications.manageTemplates', 'ניהול תבניות מייל'],
  ] }),
  Object.freeze({ id: 'contacts', label: 'אנשי קשר מוסדיים', permissions: [
    ['contacts.view', 'צפייה באנשי קשר מוסדיים'],
    ['contacts.create', 'יצירת אנשי קשר'],
    ['contacts.edit', 'עריכת אנשי קשר'],
    ['contacts.archive', 'ארכוב אנשי קשר'],
    ['contacts.merge', 'מיזוג אנשי קשר כפולים'],
    ['contacts.viewSharedHistory', 'צפייה בהיסטוריה משותפת של איש קשר'],
  ] }),
  Object.freeze({ id: 'initiatives', label: 'תכניות ארוכות טווח', permissions: [
    ['initiatives.view', 'צפייה בתכניות שבהן המשתמש משתתף'],
    ['initiatives.viewAll', 'צפייה בכלל תכניות המוסד'],
    ['initiatives.create', 'יצירת תכנית ארוכת טווח'],
    ['initiatives.edit', 'עריכת תכנית'],
    ['initiatives.manageParticipants', 'ניהול משתתפים ואחריות'],
    ['initiatives.createMilestones', 'יצירת אבני דרך'],
    ['initiatives.approveMilestones', 'אישור אבני דרך'],
    ['initiatives.changeHealth', 'שינוי מצב התכנית'],
    ['initiatives.createTemplate', 'יצירת תבנית תכנית'],
    ['initiatives.duplicate', 'שכפול תכנית'],
    ['initiatives.archive', 'סגירה וארכוב תכנית'],
  ] }),
  Object.freeze({ id: 'academicYears', label: 'שנות לימודים', permissions: [
    ['academicYears.view', 'צפייה בשנות לימודים'],
    ['academicYears.manage', 'ניהול שנות לימודים'],
  ] }),
  Object.freeze({ id: 'classes', label: 'כיתות', permissions: [
    ['classes.view', 'צפייה בכיתות'],
    ['classes.create', 'יצירת כיתות'],
    ['classes.update', 'עריכת כיתות'],
    ['classes.archive', 'ארכוב ושחזור כיתות'],
    ['classes.assignTeacher', 'שיוך מחנך וצוות'],
    ['classes.promote', 'העלאת כיתה לשנה חדשה'],
  ] }),
  Object.freeze({ id: 'students', label: 'תלמידים', permissions: [
    ['students.view', 'צפייה בתלמידים'],
    ['students.viewSensitiveFields', 'צפייה בפרטי זיהוי רגישים'],
    ['students.create', 'יצירת תלמידים'],
    ['students.edit', 'עריכת תלמידים'],
    ['students.bulkImport', 'ייבוא תלמידים מאסיבי'],
    ['students.manageClasses', 'ניהול שיוך תלמידים לכיתות'],
    ['students.manageStatus', 'ניהול סטטוס תלמידים'],
    ['students.managePersonalFile', 'ניהול התיק האישי'],
    ['students.manageResume', 'ניהול קורות החיים'],
    ['students.update', 'עריכת תלמידים'],
    ['students.archive', 'ארכוב תלמידים'],
    ['students.transferClass', 'העברה בין כיתות'],
    ['students.promote', 'העלאה לשנה חדשה'],
    ['students.markGraduate', 'סימון כבוגר'],
    ['students.graduateClass', 'הפיכת כיתה שלמה לבוגרים'],
    ['students.restoreGraduate', 'ביטול סטטוס בוגר ושיבוץ מחדש'],
    ['students.markWithdrawn', 'סימון כפורש או עבר מוסד'],
    ['students.markDropout', 'סימון כנושר'],
    ['students.restore', 'החזרה לפעילות'],
    ['students.managePrograms', 'ניהול מגמות ותוכניות לימוד'],
    ['students.addNotes', 'הוספת הערות'],
    ['students.viewSensitiveNotes', 'צפייה בהערות רגישות'],
  ] }),
  Object.freeze({ id: 'grades', label: 'ציונים ומיפויים', permissions: [
    ['grades.view', 'צפייה בציונים'],
    ['grades.edit', 'עריכת ציוני תלמידים'],
    ['gradebooks.manage', 'ניהול מקצועות, רכיבים ונוסחאות'],
  ] }),
  Object.freeze({ id: 'outcomes', label: 'תעודות ומדדי זכאות', permissions: [
    ['outcomes.view', 'צפייה בהגדרות ובמדדי זכאות'],
    ['outcomes.manageDefinitions', 'ניהול הגדרות תעודה'],
    ['outcomes.assignToClass', 'שיוך תעודות ויעדים לכיתה'],
    ['outcomes.calculate', 'חישוב זכאות'],
    ['outcomes.manualApproval', 'אישור זכאות ידני'],
    ['outcomes.viewStudentResults', 'צפייה בתוצאות זכאות אישיות'],
  ] }),
  Object.freeze({ id: 'personalFile', label: 'תיק אישי', permissions: [
    ['personalFile.view', 'צפייה בתיק אישי'],
    ['personalFile.manage', 'ניהול תיק אישי'],
    ['personalFile.upload', 'העלאת מסמכים'],
    ['personalFile.archiveDocuments', 'ארכוב מסמכים'],
  ] }),
  Object.freeze({ id: 'cv', label: 'קורות חיים', permissions: [
    ['cv.view', 'צפייה בקורות חיים'],
    ['cv.create', 'יצירת קורות חיים'],
    ['cv.edit', 'עריכת קורות חיים'],
    ['cv.deleteDraft', 'מחיקת טיוטה'],
    ['cv.finalize', 'סימון גרסה כסופית'],
    ['cv.exportPdf', 'הפקת PDF'],
    ['cv.manageSkills', 'ניהול מיומנויות'],
    ['cv.manageExperience', 'ניהול ניסיון'],
    ['cv.manageRecommendations', 'ניהול המלצות'],
    ['cv.manageCredentials', 'ניהול הסמכות'],
    ['cv.bulkGenerate', 'יצירה מרוכזת לכיתה'],
  ] }),
  Object.freeze({ id: 'cvTemplates', label: 'תבניות קורות חיים', permissions: [
    ['cvTemplates.view', 'צפייה בתבניות'],
    ['cvTemplates.create', 'יצירת תבניות'],
    ['cvTemplates.update', 'עריכת תבניות'],
    ['cvTemplates.archive', 'ארכוב תבניות'],
    ['cvTemplates.manageSchoolTemplates', 'ניהול תבניות מוסדיות'],
  ] }),
  Object.freeze({ id: 'roles', label: 'תפקידים והרשאות', permissions: [
    ['roles.view', 'צפייה בתפקידים'],
    ['roles.create', 'יצירת תפקידים'],
    ['roles.update', 'עריכת והעתקת תפקידים'],
    ['roles.assign', 'שיוך תפקידים למשתמשים'],
    ['roles.archive', 'ארכוב תפקידים'],
    ['roles.manage', 'ניהול הגדרות תפקידים'],
    ['roles.delegateAssignments', 'האצלת סמכות להקצאת תפקידים'],
    ['permissions.delegate', 'האצלת הרשאות מאושרות'],
  ] }),
  Object.freeze({ id: 'files', label: 'קבצים ותיקיות', permissions: [
    ['files.view', 'צפייה בקבצים ותיקיות'],
    ['files.create', 'יצירת קבצים ותיקיות'],
    ['files.edit', 'עריכת קבצים'],
    ['files.delete', 'מחיקת קבצים ותיקיות'],
    ['files.share', 'שיתוף קבצים ותיקיות'],
    ['files.managePermissions', 'ניהול הרשאות נקודתיות'],
  ] }),
  Object.freeze({ id: 'calendar', label: 'לוח שנה', permissions: [
    ['calendar.view', 'צפייה בלוח השנה'],
    ['calendar.create', 'יצירת אירועים'],
    ['calendar.edit', 'עריכת אירועים'],
    ['calendar.manageSchoolCalendar', 'ניהול לוח השנה המוסדי'],
  ] }),
  Object.freeze({ id: 'institution', label: 'ניהול המוסד', permissions: [
    ['institution.settings', 'ניהול הגדרות המוסד'],
    ['institution.audit.view', 'צפייה ביומן ביקורת'],
    ['institution.permissionPreview', 'תצוגה מקדימה כמשתמש'],
  ] }),
  Object.freeze({ id: 'collectiveBrain', label: 'מוח משותף', permissions: [
    ['collectiveBrain.manage', 'יצירה וניהול של לוחות, שאלות ותשובות'],
  ] }),
  Object.freeze({ id: 'forum', label: 'פורום בתי הספר', permissions: [
    ['forum.access', 'גישה לפורום'],
    ['forum.read', 'קריאת דיונים'],
    ['forum.createThread', 'פתיחת דיון'],
    ['forum.reply', 'תגובה לדיון'],
    ['forum.editOwnPost', 'עריכת פוסט עצמי'],
    ['forum.deleteOwnPost', 'מחיקת פוסט עצמי'],
    ['forum.uploadAttachment', 'העלאת קובץ לפורום'],
    ['forum.createFolder', 'יצירת תיקיית פורום'],
    ['forum.editFolder', 'עריכת תיקיית פורום'],
    ['forum.pinThread', 'הצמדת דיון'],
    ['forum.lockThread', 'נעילת דיון'],
    ['forum.moderate', 'ניהול ודיווחי תוכן'],
    ['forum.managePermissions', 'ניהול הרשאות פורום'],
    ['forum.approveDelegates', 'אישור נציגי מוסדות'],
    ['forum.viewAuditLog', 'צפייה ביומן פעולות הפורום'],
  ] }),
  Object.freeze({ id: 'support', label: 'תמיכת המערכת', permissions: [
    ['support.create', 'פתיחת פנייה לתמיכת המערכת'],
    ['support.viewOwnSchool', 'צפייה בפניות התמיכה של המוסד'],
  ] }),
]);

export const GRANULAR_PERMISSION_KEYS = Object.freeze(
  PERMISSION_GROUPS.flatMap(group => group.permissions.map(([key]) => key)),
);

export const LEGACY_PERMISSION_KEYS = Object.freeze([
  'calendar_view', 'calendar_edit', 'categories_view', 'categories_edit',
  'staff_view', 'staff_edit', 'staff_delete', 'tasks_view', 'tasks_edit', 'tasks_assign',
  'teams_view', 'teams_edit', 'files_view', 'files_upload', 'files_delete',
  'messages_send', 'messages_delete', 'holidays_view', 'holidays_edit',
  'data_mapping_view', 'data_mapping_edit', 'classes_view', 'classes_create',
  'classes_update', 'classes_archive', 'classes_assign_teacher', 'students_view',
  'students_edit', 'students_create', 'students_update', 'students_archive',
  'students_transfer_class', 'students_manage_programs', 'students_add_notes',
  'students_view_notes', 'attendance_create', 'attendance_view', 'attendance_edit',
  'attendance_manage_legend', 'attendance_manage_dates', 'attendance_block_days',
  'schools_manage', 'settings_edit',
]);

// Direct permission changes made by Zoki update the modern capability and its
// legacy UI alias together. This keeps older navigation checks and newer
// server-side authorization decisions in agreement.
export const PERMISSION_COMPATIBILITY_ALIASES = Object.freeze({
  'calendar.view': Object.freeze(['calendar_view']),
  'calendar.edit': Object.freeze(['calendar_edit']),
  'tasks.viewOwn': Object.freeze(['tasks_view']),
  'tasks.editAll': Object.freeze(['tasks_edit']),
  'tasks.assign': Object.freeze(['tasks_assign']),
  'staff.view': Object.freeze(['staff_view']),
  'staff.edit': Object.freeze(['staff_edit']),
  'staff.remove': Object.freeze(['staff_delete']),
  'files.view': Object.freeze(['files_view']),
  'files.create': Object.freeze(['files_upload']),
  'files.delete': Object.freeze(['files_delete']),
  'classes.view': Object.freeze(['classes_view']),
  'classes.create': Object.freeze(['classes_create']),
  'classes.update': Object.freeze(['classes_update']),
  'classes.archive': Object.freeze(['classes_archive']),
  'classes.assignTeacher': Object.freeze(['classes_assign_teacher']),
  'students.view': Object.freeze(['students_view']),
  'students.create': Object.freeze(['students_create']),
  'students.edit': Object.freeze(['students_edit']),
  'students.update': Object.freeze(['students_update']),
  'students.archive': Object.freeze(['students_archive']),
  'students.transferClass': Object.freeze(['students_transfer_class']),
  'students.managePrograms': Object.freeze(['students_manage_programs']),
  'students.addNotes': Object.freeze(['students_add_notes']),
  'students.viewSensitiveNotes': Object.freeze(['students_view_notes']),
  'institution.settings': Object.freeze(['settings_edit']),
});

const LEGACY_DIRECT_PERMISSION_LABELS = Object.freeze({
  categories_view: ['קטגוריות לוח שנה', 'צפייה בקטגוריות'],
  categories_edit: ['קטגוריות לוח שנה', 'עריכת קטגוריות'],
  teams_view: ['צוותים', 'צפייה בצוותים'],
  teams_edit: ['צוותים', 'ניהול צוותים'],
  messages_send: ['הודעות', 'שליחת הודעות'],
  messages_delete: ['הודעות', 'מחיקת הודעות'],
  holidays_view: ['חופשות וחגים', 'צפייה בחופשות ובחגים'],
  holidays_edit: ['חופשות וחגים', 'עריכת חופשות וחגים'],
  data_mapping_view: ['מיפוי נתונים', 'צפייה במיפוי נתונים'],
  data_mapping_edit: ['מיפוי נתונים', 'עריכת מיפוי נתונים'],
  attendance_create: ['נוכחות', 'יצירת גיליון נוכחות'],
  attendance_view: ['נוכחות', 'צפייה בנוכחות'],
  attendance_edit: ['נוכחות', 'עריכת נוכחות'],
  attendance_manage_legend: ['נוכחות', 'ניהול מקרא נוכחות'],
  attendance_manage_dates: ['נוכחות', 'ניהול תאריכי נוכחות'],
  attendance_block_days: ['נוכחות', 'חסימת ימי נוכחות'],
  schools_manage: ['ניהול המוסד', 'ניהול מוסדות'],
});

const compatibilityAliasKeys = new Set(Object.values(PERMISSION_COMPATIBILITY_ALIASES).flat());

export const DIRECT_PERMISSION_DEFINITIONS = Object.freeze([
  ...PERMISSION_GROUPS.flatMap(group => group.permissions.map(([key, label]) => Object.freeze({
    key,
    label,
    group: group.label,
    keys: Object.freeze([key, ...(PERMISSION_COMPATIBILITY_ALIASES[key] || [])]),
  }))),
  ...Object.entries(LEGACY_DIRECT_PERMISSION_LABELS)
    .filter(([key]) => !compatibilityAliasKeys.has(key))
    .map(([key, [group, label]]) => Object.freeze({ key, label, group, keys: Object.freeze([key]) })),
]);

export function directPermissionDefinition(permissionKey) {
  return DIRECT_PERMISSION_DEFINITIONS.find(item => item.key === permissionKey) || null;
}

export const ALL_PERMISSION_KEYS = Object.freeze([
  ...new Set([...LEGACY_PERMISSION_KEYS, ...GRANULAR_PERMISSION_KEYS]),
]);
